config/routes.rb
Rails.application.routes.draw do
  root 'links#new'
  resources :links, only: [:create, :show, :index], param: :slug
  get '/:hash_key' => 'links#forward', as: :shortened_url

  namespace :admin do
    resources :links, only: [:show, :expire], param: :slug do
      member do
        put :expire
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  has_one :stat
  before_create :generate_next_key, :set_slug
  before_validation :add_default_url_protocol
  validates :hash_key, uniqueness: { case_sensitive: false }

  URL_REGEXP = /\A((http|https):\/\/)*[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix
  validates :original_link, format: { with: URL_REGEXP, message: 'You provided invalid URL' }

  after_update :clear_cache

  def add_default_url_protocol
    unless self.original_link[/\Ahttp:\/\//] || self.original_link[/\Ahttps:\/\//]
      self.original_link = "http://#{self.original_link}"
    end
  end

  def generate_next_key
    loop do
      self.hash_key = generate_key(self.original_link)
      break unless Link.where(hash_key: hash_key).exists?
    end
  end

  def to_param
    slug
  end

  def clear_cache
    Rails.cache.delete(self.class.redis_url_key(hash_key))
  end

  def self.redis_url_key(hash_key)
    'link:' + hash_key + ':url'
  end

  def self.fetch_link!(hash_key)
    Rails.cache.fetch(redis_url_key(hash_key), expire_in: 1.day) do
      Link.find_by!(hash_key: hash_key)
    end
  end

  private

  def generate_key(long_url)
    chars = ('a'..'z').to_a + ('0'..'9').to_a + ('A'..'Z').to_a
    random_seed = Time.now.to_s

    # MD5 Hash the long_url into a 32 character string
    hex = Digest::MD5.hexdigest(long_url + random_seed)

    # Divide the hash into 4 parts
    sub_hex_len = hex.length / 8
    short_str = Array.new(4)

    # Interate thru the 4 parts
    sub_hex_len.times do |i| 
      out_chars = ""
      j = i + 1
      sub_hex = hex[i * 8...j * 8]
      # Bit and operation between 0x3FFFFFFF(30) and the base-16 string
      # Ignore the chars beyond 30
      idx = 0x3FFFFFFF & sub_hex.to_i(16)
      # 30 chars are divided into 6 parts
      6.times {
        index = 0x0000003D & idx
        out_chars += chars[index]
        idx = idx >> 5
      }
      # Get 4 keys
      short_str[i] = out_chars
    end
    short_str.sample
  end

  def set_slug
    loop do
      self.slug = SecureRandom.uuid
      break unless Link.where(slug: slug).exists?
    end
  end
end

app/models/stat.rb
class Stat < ApplicationRecord
  belongs_to :link
  MAX_CACHE_SIZE = 100

  after_update :clear_cache

  def increment_counter(hash_key)
    redis = Redis.current
    key = redis_counter_key(hash_key)
    current_count = redis.incr(key).to_i
    if current_count >= MAX_CACHE_SIZE
      self.count += current_count
      self.save
      redis.set(key, "0")
    end
  end

  def redis_counter_key(hash_key)
    'link:' + hash_key + ':counter'
  end

  def real_count
    redis_count = Redis.current.get(redis_counter_key(self.link.hash_key)).to_i
    db_count = self.count || 0
    db_count + redis_count
  end

  def self.fetch_link_stat(link)
    Rails.cache.fetch("stat:#{link.id}", expire_in: 1.hour) do
      link.stat
    end
  end

  def clear_cache
    Rails.cache.delete("stat:#{self.link.id}")
  end
end

app/controllers/admin/links_controller.rb
class Admin::LinksController < ApplicationController
  before_action :set_link, only: [:show, :expire]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_link
  rescue_from ActiveRecord::RecordInvalid, with: :invalid_link

  def expire
    @link.update_attribute(:expired, true)
    redirect_to admin_link_path(@link), notice: "The shortened URL has been expired."
  end

  private

    def set_link
      @link = Link.find_by! slug: params[:slug]
    end

    def link_params
      params.require(:link).permit(:original_link, :hash_key, :expired)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token

  protected

  def invalid_link
    render :json => {error: "The link doesn't exist."}, :status => :not_found
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_link
  rescue_from ActiveRecord::RecordInvalid, with: :invalid_link

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.build_stat

    if @link.save
      redirect_to @link
    else
      redirect_to root_path, notice: "Invalid URL. Please try again."
    end
  end

  def forward
    @link = Link.fetch_link!(params[:hash_key])
    if @link.expired
      invalid_link
    else
      Stat.fetch_link_stat(@link).increment_counter(params[:hash_key])
      redirect_to @link.original_link, status: :moved_permanently
    end
  end

  private

    def set_link
      @link = Link.find_by! slug: params[:slug]
    end

    def link_params
      params.require(:link).permit(:original_link, :hash_key, :expired)
    end

end

app/helpers/admin/links_helper.rb
module Admin::LinksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_url_of(hash_key)
    shortened_url_url(hash_key)
  end
end

app/helpers/links_helper.rb
module LinksHelper
  def full_url
    request.protocol + request.host + ':' + request.optional_port.to_s + '/'
  end
end

app/views/admin/links/show.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<%= semantic_form_for :link, url: expire_admin_link_path, method: :put, html: { class: "link_form" } do |form| %>
  <%= form.inputs "Admin Operation" do %>
    <p>
      <strong>Shortened URL:</strong>
      <%= link_to display_url_of(@link.hash_key), display_url_of(@link.hash_key), target: '_blank', class: 'short' %>
    </p>
    <p>
      <strong>Original URL:</strong>
      <%= link_to @link.original_link, @link.original_link, class: 'original' %>
    </p>
    <p>
      <strong>Clicks:</strong>
      <%= @link.stat.real_count %>
    </p>
    <p>
      <strong>Expired:</strong>
      <%= @link.expired %>
    </p>
  <% end %>
  <% unless @link.expired %>
    <%= form.actions do %>
      <li><%= form.submit "Expire" %></li>
    <% end %>
  <% end %>
<% end %>


<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Link Shortener</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <h1>Link Shortener</h1>
    </header>
    <section class="content">
    <main class='<%= controller.controller_name %>'>
        <%= yield %>
      </main>
    </section>
  </body>
</html>

app/views/links/create.js.erb
$("<%= escape_javascript(render @link) %>").prependTo("#links");
$('#has-error').removeAttr('id');
$('#create_link')[0].reset();
$('span.help-block')[0].remove();
$('span.help-block')[1].remove();

app/views/links/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<%= form_with(model: @link, id: "create_link", class: "link_form", local: true) do |f| %>
  <dl>
    <dd>
      <%= f.text_field :original_link, placeholder: "Paste a URL to shorten it" %>
    </dd>
  </dl>
  <fieldset class="actions">
    <%= f.submit %>
    <input type="reset" value="Clear">
  </fieldset>
<% end %>

app/views/links/new.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<%= form_with(model: @link, id: "create_link", class: "link_form", local: true) do |f| %>
  <dl>
    <dd>
      <%= f.text_field :original_link, placeholder: "Paste a URL to shorten it" %>
    </dd>
  </dl>
  <fieldset class="actions">
    <%= f.submit %>
    <input type="reset" value="Clear">
  </fieldset>
<% end %>

app/views/links/show.html.erb
<p>
  <strong>Shortened URL:</strong>
  <%= link_to display_url_of(@link.hash_key), display_url_of(@link.hash_key), target: '_blank', class: 'short' %>
</p>

<p>
  <strong>Original URL:</strong>
  <%= link_to @link.original_link, @link.original_link, class: 'original' %>

</p>

<p>
  <strong>Admin URL:</strong>
  <%= link_to admin_link_url(@link), admin_link_url(@link), class: 'admin' %>
</p>

<%= link_to 'Back', root_path %>